# This script was generated by crazy-complete.
# crazy-complete: A tool that creates robust and reliable autocompletion scripts for Bash, Fish and Zsh.
# For more information, visit: https://github.com/crazy-complete/crazy-complete

function _ldc__query

  set -l positionals
  set -l having_options
  set -l option_values

  set -l options $argv[1]
  set -e argv[1]

  set -l cmd $argv[1]
  set -e argv[1]

  set -l my_cache_key "$(commandline -b) $options"

  if test "$__QUERY_CACHE_KEY" = "$my_cache_key"
    set positionals    $__QUERY_CACHE_POSITIONALS
    set having_options $__QUERY_CACHE_HAVING_OPTIONS
    set option_values  $__QUERY_CACHE_OPTION_VALUES
  else

    set -l short_opts_with_arg
    set -l short_opts_without_arg
    set -l short_opts_with_optional_arg
    set -l long_opts_with_arg
    set -l long_opts_without_arg
    set -l long_opts_with_optional_arg

    set -l option

    if test -n "$options"
      for option in (string split -- ' ' $options)
        if false
          true
        else if string match -qr -- '^--.+=$' $option
          set -a long_opts_with_arg (string replace -- '=' '' $option)
        else if string match -qr -- '^--.+=\?$' $option
          set -a long_opts_with_optional_arg (string replace -- '=?' '' $option)
        else if string match -qr -- '^--.+$' $option
          set -a long_opts_without_arg $option
        else if string match -qr -- '^-.=$' $option
          set -a short_opts_with_arg (string replace -- '=' '' $option)
        else if string match -qr -- '^-.=\?$' $option
          set -a short_opts_with_optional_arg (string replace -- '=?' '' $option)
        else if string match -qr -- '^-.$' $option
          set -a short_opts_without_arg $option
        end
      end
    end

    set -l cmdline (commandline -poc)
    set -l cmdline_count (count $cmdline)

    set -l argi 2 # cmdline[1] is command name
    while test $argi -le $cmdline_count
      set -l arg "$cmdline[$argi]"
      set -l have_trailing_arg (test $argi -lt $cmdline_count && echo true || echo false)

      switch $arg
        case '-'
          set -a positionals -
        case '--'
          set -a positionals $cmdline[$(math $argi + 1)..]
          break
        case '--*=*'
          set -l split (string split -m 1 -- '=' $arg)
          set -a having_options $split[1]
          set -a option_values "$split[2]"
        case '--*'
          if contains -- $arg $long_opts_with_arg
            if $have_trailing_arg
              set -a having_options $arg
              set -a option_values $cmdline[(math $argi + 1)]
              set argi (math $argi + 1)
            end
          else
            set -a having_options $arg
            set -a option_values ''
          end
        case '-*'
          set -l end_of_parsing false

          set -l arg_length (string length -- $arg)
          set -l i 2
          while not $end_of_parsing; and test $i -le $arg_length
            set -l option "-$(string sub -s $i -l 1 -- $arg)"
            set -l trailing_chars "$(string sub -s (math $i + 1) -- $arg)"

            if contains -- $option $short_opts_without_arg
              set -a having_options $option
              set -a option_values ''
            else if contains -- $option $short_opts_with_arg
              set end_of_parsing true

              if test -n "$trailing_chars"
                set -a having_options $option
                set -a option_values $trailing_chars
              else if $have_trailing_arg
                set -a having_options $option
                set -a option_values $cmdline[(math $argi + 1)]
                set argi (math $argi + 1)
              end
            else if contains -- $option $short_opts_with_optional_arg
              set end_of_parsing true
              set -a having_options $option
              set -a option_values "$trailing_chars" # may be empty
            end

            set i (math $i + 1)
          end
        case '*'
          set -a positionals $arg
      end

      set argi (math $argi + 1)
    end

    set -g __QUERY_CACHE_POSITIONALS    $positionals
    set -g __QUERY_CACHE_HAVING_OPTIONS $having_options
    set -g __QUERY_CACHE_OPTION_VALUES  $option_values
    set -g __QUERY_CACHE_KEY            $my_cache_key
  end

  switch $cmd
    case 'has_option'
      for option in $having_options
        contains -- $option $argv && return 0
      end

      return 1
    case 'num_of_positionals'
      switch (count $argv)
        case 0
          count $positionals
        case 2
          if contains -- $argv[1] -lt -le -eq -ne -gt -ge;
            test (count $positionals) $argv[1] $argv[2] && return 0 || return 1
          end
      end
  end
end

set -l prog 'ldc'
set -l query '_ldc__query'

# Delete existing completions
complete -c $prog -e

# Generally disable file completion
complete -c $prog -x

# command ldc
set -l opts "-d --detach --docker-in-docker --dry-run --extra-port-mappings= -h --help -m --mount-home -P= --password= -p= --port= -u= --user="
set -l C000 "not $query '$opts' has_option -d --detach"
set -l C001 "not $query '$opts' has_option --docker-in-docker"
set -l C002 "not $query '$opts' has_option --dry-run"
set -l C003 "not $query '$opts' has_option --extra-port-mappings"
set -l C004 "not $query '$opts' has_option -h --help"
set -l C005 "not $query '$opts' has_option -m --mount-home"
set -l C006 "not $query '$opts' has_option -P --password"
set -l C007 "not $query '$opts' has_option -p --port"
set -l C008 "not $query '$opts' has_option -u --user"
set -l C009 "$query '$opts' num_of_positionals -eq 0"
complete -c $prog -n $C000 -s d -l detach -d 'Run container in background and print container ID.' -f
complete -c $prog -n $C001 -l docker-in-docker -d 'Mount docker.sock to allow running Docker in Docker containers.' -f
complete -c $prog -n $C002 -l dry-run -d 'Print out the docker command without running it.' -f
complete -c $prog -n $C003 -l extra-port-mappings -d 'Extra port mappings.' -x
complete -c $prog -n $C004 -s h -l help -d 'help for ldc' -f
complete -c $prog -n $C005 -s m -l mount-home -d 'Mount /home on the host as /home_host in the Docker container.' -f
complete -c $prog -n $C006 -s P -l password -d 'The default password for the user (to create in the Docker container).' -x
complete -c $prog -n $C007 -s p -l port -d 'The port on the Docker host to forward to the port inside the Docker container.' -x
complete -c $prog -n $C008 -s u -l user -d 'The user to create in the Docker container.' -x
complete -c $prog -n $C009 -x -a 'dclong/jupyterhub-ds dclong/vscode-server'

# vim: ft=fish ts=2 sts=2 sw=2 et
