# ldc completion                                           -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_ldc_completions_filter() {
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  if [[ "${cur:0:1}" == "-" ]]; then
    echo "$words"

  else
    for word in $words; do
      [[ "${word:0:1}" != "-" ]] && result+=("$word")
    done

    echo "${result[*]}"

  fi
}

_ldc_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")
  local compline="${compwords[*]}"

  case "$compline" in
    'dclong/jupyterhub-ds'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_ldc_completions_filter "-d --detach --docker-in-docker --dry-run --extra-port-mappings -h --help -m --mount-home -P --password -p --port -u --user")" -- "$cur")
      ;;

    'dclong/vscode-server'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_ldc_completions_filter "-d --detach --docker-in-docker --dry-run --extra-port-mappings -h --help -m --mount-home -P --password -p --port -u --user")" -- "$cur")
      ;;

    *)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_ldc_completions_filter "dclong/jupyterhub-ds dclong/vscode-server -d --detach --docker-in-docker --dry-run --extra-port-mappings -h --help -m --mount-home -P --password -p --port -u --user")" -- "$cur")
      ;;

  esac
} &&
  complete -F _ldc_completions ldc

# ex: filetype=sh
