name: shellcheck
on:
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    name: lint shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install shfmt
        run: sudo apt update && sudo apt install -y shfmt
      - name: Check Shell Formatting
        run: shfmt -i 4 -ci -d install_icon.sh
      - name: Lint Shell Script
        run: shellcheck install_icon.sh
